name: pkg

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/pqx
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gob-
      - name: Test
        run: go test ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
